### ISSUE TITLE
snap install AWT error

### ISSUE THREAD

**Issue by syffs** [snapcrafters/jenkins#21]
I simply installed jenkins with `sudo snap install jenkins` on Ubuntu 18.04.3 LTS

here is the error
```
AWT is not properly configured on this server. perhaps you need to run your container with "-Djava.awt.headless=true"?
java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
Caused: java.lang.InternalError
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/java.awt.Font.getFont2D(Font.java:497)
	at java.desktop/java.awt.Font.getFamily(Font.java:1410)
	at java.desktop/java.awt.Font.getFamily_NoClientCode(Font.java:1384)
	at java.desktop/java.awt.Font.getFamily(Font.java:1376)
	at java.desktop/java.awt.Font.toString(Font.java:1869)
	at hudson.util.ChartUtil.<clinit>(ChartUtil.java:260)
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:957)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:922)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:365)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at winstone.Launcher.<init>(Launcher.java:187)
	at winstone.Launcher.main(Launcher.java:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:375)
	at Main.main(Main.java:151)
```

@popey any insight ?

**Comment by briemens** [comment]
Same for me! :-(

If you check the running process list you can see Jenkins started with the suggested headless flag already.

```
/snap/jenkins/306/usr/lib/jvm/java-11-openjdk/bin/java -DJENKINS_HOME=/var/snap/jenkins/306 -Djava.awt.headless=true -jar /snap/jenkins/306/jenkins.war
```

**Comment by popey** [comment]
Strange. Works fine here. Can you backup your data and remove and install jenkins? I had this a while back and re-installing magically worked :s: 
But do backup your data! :D

**Comment by briemens** [comment]
Hi @popey! Thanks for your reply.

Are you by any chance running the Jenkins snap on a headless 18.04 server install or on Ubuntu desktop?

What I did was install Ubuntu server 18.04 and install the Jenkins snap to get this error. Nothing else.

**Comment by popey** [comment]
On a headless 18.04 server. It's an install I've had for a long while. I've tested jenkins on it many times.

**Comment by ruipires** [comment]
I am experiencing this issue too.
Headless 18.04 server, installed via vagrant (the exact box used is bento/ubuntu-18.04)

Nothing else installed, just run this command:
sudo snap install jenkins --classic

**Comment by AwiOnline** [comment]
I have the same issue.
fresh install Ubuntu 18.04.3 and
sudo snap install jenkins --classic

**Comment by kz6fittycent** [comment]
Closing this issue due to age and may not be valid anymore. No further issues noted or reported since 2019.
